apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: {{ .Values.HorizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.HorizontalPodAutoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.HorizontalPodAutoscaler.averageUtilization }}