configmap:
  cart_endpoint: "cart:8080"
  db_host: "mysql"
deployment:
  relicas: "1"
  image: krishna88s/shipping
  imageVersion: "1.1.0"
  cause: "this version is 1.1.0"
HorizontalPodAutoscaler:
  minReplicas: "1"
  maxReplicas: "10"
  averageUtilization: "10"  
