apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # this labels is for replicaset
  labels:
    project: roboshop
    tier: backend
    component: catalogue
    environment: dev
  annotations:
    kubernetes.io/change-cause: {{ .Values.deployment.cause }}  
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      # these labels is for replicaset to select the pods
      project: roboshop
      tier: backend
      component: catalogue
      environment: dev
  template:
    metadata:
    # these for pod defination
      labels:
        project: roboshop
        tier: backend
        component: catalogue
        environment: dev
    spec:
      containers:
      - name: catalogue
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 4
          periodSeconds: 10
          initialDelaySeconds: 15   
        livenessProbe: 
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 4
          periodSeconds: 10   
        envFrom:
        - configMapRef:
            name: catalogue-configmap


