apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
    environment: dev
spec:
  selector:
      project: roboshop
      tier: backend
      component: catalogue
      environment: dev

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
