apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: nginx
    environment: dev
spec:
  targetType: ip
  serviceRef:
    name: frontend # route traffic to the awesome-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:220719767845:targetgroup/roboshop-dev-frontend/966a475fb9eae0e4