apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: redis
    environment: dev
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: database
    component: redis
    environment: dev
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: redis
    environment: dev
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: database
      component: redis
      environment: dev # has to match .spec.template.metadata.labels
  serviceName: "redis-headless"
  #replicas: 4
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: redis
        environment: dev # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: krishna88s/redis:1.1.0
        volumeMounts:
        - name: redis
          mountPath: /data
  #PVC         
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: redis
    environment: dev
spec:
  selector:
    project: roboshop
    tier: database
    component: redis
    environment: dev
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379