apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-configmap
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
    environment: dev

data:
  CART_ENDPOINT: {{ .Values.configmap.cart_endpoint }}
  DB_HOST: {{ .Values.configmap.db_host }}
