apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: roboshop
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3AK
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjMK
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
    environment: dev
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: database
    component: rabbitmq
    environment: dev
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
    environment: dev
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: database
      component: rabbitmq
      environment: dev # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless"

  #replicas: 4
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: rabbitmq
        environment: dev # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: rabbitmq
        image: krishna88s/rabbitmq:1.1.0
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123  
  #PVC         
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
    environment: dev
spec:
  selector:
    project: roboshop
    tier: database
    component: rabbitmq
    environment: dev
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672